name: Issue 5
on: push

jobs:
  # Setup matrix
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setup-matrix.outputs.matrix }}
    steps:
      - id: setup-matrix
        uses: druzsan/setup-matrix@feature/use-python-dockerfile
        with:
          matrix: |
            include:
              - os: linux
                cpu: amd64
                run-on: ubuntu-latest
                shell: bash -e
              - os: macos
                cpu: amd64
                run-on: macos-latest
                shell: bash -e
              - os: windows
                cpu: amd64
                run-on: windows-latest
                shell: msys2

  # Setup python and print version
  build:
    needs: setup-matrix
    strategy:
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
    runs-on: ${{ matrix.run-on }}
    name: '${{ matrix.os }}-${{ matrix.cpu }}-${{ matrix.shell }}'
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

  build-builtin:
    strategy:
      matrix:
        include:
          - os: linux
            cpu: amd64
            run-on: ubuntu-latest
            shell: bash -e
          - os: macos
            cpu: amd64
            run-on: macos-latest
            shell: bash -e
          - os: windows
            cpu: amd64
            run-on: windows-latest
            shell: msys2
    runs-on: ${{ matrix.run-on }}
    name: '${{ matrix.os }}-${{ matrix.cpu }}-${{ matrix.shell }}'
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
